- id: dotnet-reformat
  name: dotnet-reformat
  description: Relies on csproj files and dotnet-format tool, csproj file as arg
  entry: dotnet dotnet-format -p
  pass_filenames: false
  language: system
  files: '\.cs'
